Addressed comments

diff --git a/.github/workflows/e2etest-run-tests.yml b/.github/workflows/e2etest-run-tests.yml
--- a/.github/workflows/e2etest-run-tests.yml
+++ b/.github/workflows/e2etest-run-tests.yml
@@ -118,14 +118,23 @@ jobs:
           DOTNET_CLI_HOME: /tmp
         working-directory: ./src/tests/e2etest
         run: |
+          function checkResult(){
+            if [ $result -ne 0 ]; then
+              echo '::error title=E2E Test Failure::The E2E tests failed at run number $runNumber'
+              exit $result
+            fi
+          }
+          result=0
           if [ ${{ inputs.repeatForXHours }} -gt 0 ];then
             end=`date -d "+${{inputs.repeatForXHours}} hours" +%s`
             while [ $(date +%s) -lt $end ]; do
               echo Performing test run $((++runNumber))
-              sudo E2E_OSCONFIG_IOTHUB_CONNSTR="${{ steps.hub-identity.outputs.iothubowner_connection_string }}" E2E_OSCONFIG_DEVICE_ID="${{ steps.get-test-data.outputs.device_id }}" E2E_OSCONFIG_DISTRIBUTION_NAME="${{ matrix.distroName }}" E2E_OSCONFIG_TWIN_TIMEOUT=${{ secrets.TWIN_TIMEOUT }} dotnet test ${{ steps.get-test-data.outputs.test_filter }} --logger "trx;LogFileName=test-results-${{ matrix.distroName }}-$runNumber.trx;verbosity=detailed" --logger "console;verbosity=detailed"
+              result=`sudo E2E_OSCONFIG_IOTHUB_CONNSTR="${{ steps.hub-identity.outputs.iothubowner_connection_string }}" E2E_OSCONFIG_DEVICE_ID="${{ steps.get-test-data.outputs.device_id }}" E2E_OSCONFIG_DISTRIBUTION_NAME="${{ matrix.distroName }}" E2E_OSCONFIG_TWIN_TIMEOUT=${{ secrets.TWIN_TIMEOUT }} dotnet test ${{ steps.get-test-data.outputs.test_filter }} --logger "trx;LogFileName=test-results-${{ matrix.distroName }}-$runNumber.trx;verbosity=detailed" --logger "console;verbosity=detailed"`
+              checkResult
             done
           else
-            sudo E2E_OSCONFIG_IOTHUB_CONNSTR="${{ steps.hub-identity.outputs.iothubowner_connection_string }}" E2E_OSCONFIG_DEVICE_ID="${{ steps.get-test-data.outputs.device_id }}" E2E_OSCONFIG_DISTRIBUTION_NAME="${{ matrix.distroName }}" E2E_OSCONFIG_TWIN_TIMEOUT=${{ secrets.TWIN_TIMEOUT }} dotnet test ${{ steps.get-test-data.outputs.test_filter }} --logger "trx;LogFileName=test-results-${{ matrix.distroName }}.trx;verbosity=detailed" --logger "console;verbosity=detailed"
+            result=`sudo E2E_OSCONFIG_IOTHUB_CONNSTR="${{ steps.hub-identity.outputs.iothubowner_connection_string }}" E2E_OSCONFIG_DEVICE_ID="${{ steps.get-test-data.outputs.device_id }}" E2E_OSCONFIG_DISTRIBUTION_NAME="${{ matrix.distroName }}" E2E_OSCONFIG_TWIN_TIMEOUT=${{ secrets.TWIN_TIMEOUT }} dotnet test ${{ steps.get-test-data.outputs.test_filter }} --logger "trx;LogFileName=test-results-${{ matrix.distroName }}.trx;verbosity=detailed" --logger "console;verbosity=detailed"`
+            checkResult
           fi
 
       - name: Stop performance sampling
